### ISSUE TITLE
Action Button: Configurability for some Box-Sizing properties

### ISSUE THREAD

**Issue by danielejdm** [MscrmTools/PCF-Controls#108]
Perhaps it might be nice to have the ability to configure some sizing parameters for the box. 
I have a scenario where I want to show only the icon; obviously this is possible by not providing any text for the related parameter. However, the box seems to have a minimum size. In fact, if I configure a background color, the whole box is noticeable.
As in this screenshot, for example I would like to have a minimal box and align the icon to the left.
Or is it possible to have the same result with the current parameters?

![image](https://user-images.githubusercontent.com/34159960/202172078-24f942ab-0526-49d7-bb34-e05fba4e4478.png)

**Comment by MscrmTools** [comment]
@danielejdm Would it fit your request like this (meaning when no text, display just the icon as an Icon button instead of a plain button) ?
![image](https://user-images.githubusercontent.com/10774317/205649297-be74e085-f1bf-4274-93dc-3d6202acf6fe.png)

As for aligning to the left, I guess you just have to hide the label for the attribute in the form
