### ISSUE TITLE
Action Button

### ISSUE THREAD

**Issue by alanrroberts** [MscrmTools/PCF-Controls#119]
Hi

Thanks for these great tools.  I was just wondering how I tell the action button not to use an icon?  If I delete the value in the field it defaults to LightningBolt. 

Thanks

Alan

**Comment by alanrroberts** [comment]
Brilliant, thanks

**Comment by MscrmTools** [comment]
Can you beta test this?
What's new:
- If no label is provided, it adds an icon button instead of a button
- If no icon is provided, should only add text
- You can set the width of the button 

[MscrmToolsPCFControls_managed.zip](https://github.com/MscrmTools/PCF-Controls/files/10210079/MscrmToolsPCFControls_managed.zip)

**Comment by alanrroberts** [comment]
Yep all of the above are working for me.  Great update, thanks for responding so quickly.
