### ISSUE TITLE
[Question] How to use the Action Button

### ISSUE THREAD

**Issue by limyandi** [MscrmTools/PCF-Controls#158]
Hi,

How do I use the Action Button?
I already created a script and load the script that contains the OnChange function
<img width="464" alt="image" src="https://github.com/MscrmTools/PCF-Controls/assets/19499685/94705a52-36a7-4c41-9f00-6ca6532ddfd4">

I have also bind the button with the onChange event
<img width="433" alt="image" src="https://github.com/MscrmTools/PCF-Controls/assets/19499685/fabde9d8-bc97-47a2-a946-bfef67a7e943">
<img width="199" alt="image" src="https://github.com/MscrmTools/PCF-Controls/assets/19499685/8e8ca15d-7a28-4898-a5fa-6ce10da962d9">

But it is still not triggering the onChange function at all, I have put in a breakpoint as well but nothing ever happens.
Your help is much appreciated, thank you.

**Comment by MscrmTools** [comment]
Everything looks correct and the onChange should be triggered. What can happen is the code does nothing because the value of the sample is "Run this!" and you button says "Copy Postal Code". So you should change that. 
Please note that the PCF configuration allows to pass an ID instead of the button label. This can be more convenient.

**Comment by limyandi** [comment]
It's working now with the ID, thank you.
