### ISSUE TITLE
checkboxes are selected on load of page 

### ISSUE THREAD

**Issue by karthickDhanapal** [MscrmTools/PCF-Controls#17]
Hi @MscrmTools ,

I have implemented the solution in my crm for N N checkbox with the subgrid, but on load of page the checkbox are selected by default. I need to be unchecked by default

**Comment by MscrmTools** [comment]
One of my colleague reported this once but I never faced this situation.
Checkboxes should be ticked only for existing relationships

**Comment by karthickDhanapal** [comment]
any idea on this??

**Comment by karthickDhanapal** [comment]
@MscrmTools both switch and checkbox having this issue

**Comment by MscrmTools** [comment]
I'm sorry but I just don't reproduce it... See screenshot below

![image](https://user-images.githubusercontent.com/10774317/88900633-f43b5580-d24f-11ea-9f5e-21625f09af9a.png)

**Comment by BugsOli** [comment]
Hello Tanguy, got exactly the same problem, here is what I have:

- Entity 1: incident
- Entity 2: new_taggingsystem (custom entity, organization owned)
- N:N relationship between both entities
- On the default case form, I've added a 1-column tab with a sub-grid to display the tags (grid set to "All Record types")
- Sub-grid uses your "Checkbox list" PCF control with the appropriate settings: label [set to the default custom entity text field], group by [set to an option set created in the custom entity], columns [set to 4], layout [set to Check boxes])

I haven't set the relationship value since my tagging system is only used for the cases.

Hth,
Thanks for your awesome work, big fan since day 1!

Olivier

**Comment by BugsOli** [comment]
I have moved the sub-grid to the first tab and reset the columns to 2, even set the relationship schema name but it's still the same.
And when I save the case, nothing gets saved in the N:N relationship...

**Comment by BugsOli** [comment]
Nevermind, found my mistake: when you add the N:N sub-grid to the form, you must specify "Only Related Records" and NOT "All Record Types"
![image](https://user-images.githubusercontent.com/40055851/92385084-836e3f80-f111-11ea-99bd-54bb20fdc561.png)

**Comment by MscrmTools** [comment]
@BugsOli Thank you for the feedback and the cause of the issue
