### ISSUE TITLE
Auto refresh the sub grid

### ISSUE THREAD

**Issue by nijos** [MscrmTools/PCF-Controls#3]
Hello,
can we do something to auto refresh the subgrid when an item is added?

**Comment by DynamicsNinja** [comment]
This can be done in an unsupported way at the moment because you need to use formcontext object that is not accessible from the control itself, you only have control context. Controls are not supposed to talk with other components (subgrid in this example) on the form.

The main purpose of the control, in my opinion, is to replace the subgrid on the form, not to co-exist with it.

**Comment by nijos** [comment]
> This can be done in an unsupported way at the moment because you need to use formcontext object that is not accessible from the control itself, you only have control context. Controls are not supposed to talk with other components (subgrid in this example) on the form.
> 
> The main purpose of the control, in my opinion, is to replace the subgrid on the form, not to co-exist with it.

Thank you, this is very detail. I got stuck at this point while trying something similar
