### ISSUE TITLE
Feature Suggestion: Filtering

### ISSUE THREAD

**Issue by improving-jeffd** [MscrmTools/PCF-Controls#7]
It would be great to have the tool request an optional Filter Attribute and Filter Value, then use those to restrict the dataset available to select from.

For example if you were editing an Opportunity record and wanted to select contacts from the Account record to identify whom you are dealing with from the Account employees. I'd imagine selecting the Contacts as the related entity, the Account Field on Contact as the field to filter by and the Account (Customer) field on the Opportunity as the value to filter by.

Does that make sense?

**Comment by MscrmTools** [comment]
it totally makes sense but Lookup field are not supported currently.
Or I can implement a lookup filter and mention it's not supported

**Comment by improving-jeffd** [comment]
Just had an additional though to this. You could support filtering by related supported attributes. In my example above an administrator could create hidden single line text fields to store the Customer Account name on Opportunity and one on Contact to store the Primary Account Name. The tool could then filter based on those two attributes.

Just my random thought for the day. :)

**Comment by MscrmTools** [comment]
Yes, it was my intention to work on this kind of feature today! Perfectly in time so!

**Comment by MscrmTools** [comment]
It should be usable with latest release

**Comment by mverbanck** [comment]
> It should be usable with latest release

He sorry to bother again, but how would it actually work? 

So for the example above we are talking about a filter with Opportunity where you want to select the contacts from the Account.

So as I've read in the documentation it's not working on a lookup as long as MS isn't supporting it but we could link it to a textfield, witht the id of the entityrefence I assume? 

So I tried for the example case to set the filter param to a lookup of account, or a text field containing the accountid.
![image](https://user-images.githubusercontent.com/11208075/172059945-d79814b3-5ed2-4b4e-bf83-359f91a5670a.png)

In both cases I seem to get the options where the field is empty instead of the options with a matching accountid.
According to the info I would expect a second configuration to do the matching, but as it is the only config containing 'filter' I honestly have no clue what parameter to use.

First time using pcf's but really like what you did here!

**Comment by MscrmTools** [comment]
@mverbanck as mentioned in documentation, there is two columns/attributes that need to be set to apply filtering: one in the dataset and one for the parent record.
I must admit I did not test since long tome if Lookup were working fine now. But if not, this PCF does not handle the use of text attribute that could contain the id of a lookup value. So I'm not expecting things to work well here
